version: "3"
services:
  mysql:
    container_name: mysql
    # M1에서만 platform 추가
    platform: linux/x86_64
    image: library/mysql:8.0.22
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: fkream
      MYSQL_PASSWORD: fkream
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    # 명령어 설정
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./mysql-root:/root

  redis:
    container_name: redis
    image: redis
    user: root
    ports:
      - 6379:6379

  zookeeper:
    container_name: local-zookeeper
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka:
    container_name: local-kafka
    image: wurstmeister/kafka:2.13-2.8.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1 # 싱글 브로커 환경
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

